site:
  title: Конспекты осенний семестр 2023
  start_page: hpc::index.adoc
content:
  sources:
  - url: .
    start_path: docs
    branches: HEAD

asciidoc:
  attributes:
    page-pagination: ''
ui:
  bundle:
    url: ./ui
